server:
  port: 8555 #API网关端口号
spring:
  application:
    name: API-Gateway

zuul:
  routes:
    serivceA:
      path: /mq/**
      serviceId: MYSTOCK-BACKGROUD-MQ
    serviceB:
      path: /ws/**
      serviceId: MYSTOCK-BACKGROUD-WS
      
eureka:
  instance:
    hostname: 127.0.0.1 #服务注册中心IP地址
    port: 8381
  client:
    registerWithEureka: false #是否向服务注册中心注册自己
    fetchRegistry: true #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/