eureka:
  instance:
    hostname: 127.0.0.1 #服务注册中心IP地址
    port: 8381
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

spring:
  profiles:
    active: local
  application:
    name: mystock-backgroud-mq
