package com.ibm.fsd.my.stock.bkg.domain;

import java.util.Date;

public class StockTradeRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_record.id
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_record.stock_id
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    private Long stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_record.buy_record_id
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    private Long buyRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_record.sell_record_id
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    private Long sellRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_record.trade_price
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    private Double tradePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_record.trade_qt
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    private Long tradeQt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_record.trade_dt
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    private Date tradeDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_record.trade_date
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    private String tradeDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_record.id
     *
     * @return the value of stock_trade_record.id
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_record.id
     *
     * @param id the value for stock_trade_record.id
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_record.stock_id
     *
     * @return the value of stock_trade_record.stock_id
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    public Long getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_record.stock_id
     *
     * @param stockId the value for stock_trade_record.stock_id
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    public void setStockId(Long stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_record.buy_record_id
     *
     * @return the value of stock_trade_record.buy_record_id
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    public Long getBuyRecordId() {
        return buyRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_record.buy_record_id
     *
     * @param buyRecordId the value for stock_trade_record.buy_record_id
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    public void setBuyRecordId(Long buyRecordId) {
        this.buyRecordId = buyRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_record.sell_record_id
     *
     * @return the value of stock_trade_record.sell_record_id
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    public Long getSellRecordId() {
        return sellRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_record.sell_record_id
     *
     * @param sellRecordId the value for stock_trade_record.sell_record_id
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    public void setSellRecordId(Long sellRecordId) {
        this.sellRecordId = sellRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_record.trade_price
     *
     * @return the value of stock_trade_record.trade_price
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    public Double getTradePrice() {
        return tradePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_record.trade_price
     *
     * @param tradePrice the value for stock_trade_record.trade_price
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    public void setTradePrice(Double tradePrice) {
        this.tradePrice = tradePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_record.trade_qt
     *
     * @return the value of stock_trade_record.trade_qt
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    public Long getTradeQt() {
        return tradeQt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_record.trade_qt
     *
     * @param tradeQt the value for stock_trade_record.trade_qt
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    public void setTradeQt(Long tradeQt) {
        this.tradeQt = tradeQt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_record.trade_dt
     *
     * @return the value of stock_trade_record.trade_dt
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    public Date getTradeDt() {
        return tradeDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_record.trade_dt
     *
     * @param tradeDt the value for stock_trade_record.trade_dt
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    public void setTradeDt(Date tradeDt) {
        this.tradeDt = tradeDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_record.trade_date
     *
     * @return the value of stock_trade_record.trade_date
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    public String getTradeDate() {
        return tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_record.trade_date
     *
     * @param tradeDate the value for stock_trade_record.trade_date
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    public void setTradeDate(String tradeDate) {
        this.tradeDate = tradeDate == null ? null : tradeDate.trim();
    }
}