package com.ibm.fsd.my.stock.bkg.domain;

public class StockPriceHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_price_history.id
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_price_history.stock_id
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private Long stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_price_history.history_date
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private String historyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_price_history.last_price
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private Double lastPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_price_history.closed_price
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private Double closedPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_price_history.top_price
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private Double topPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_price_history.low_price
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private Double lowPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_price_history.qt_total
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private Long qtTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_price_history.trade_count
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private Long tradeCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_price_history.id
     *
     * @return the value of stock_price_history.id
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_price_history.id
     *
     * @param id the value for stock_price_history.id
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_price_history.stock_id
     *
     * @return the value of stock_price_history.stock_id
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public Long getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_price_history.stock_id
     *
     * @param stockId the value for stock_price_history.stock_id
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setStockId(Long stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_price_history.history_date
     *
     * @return the value of stock_price_history.history_date
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public String getHistoryDate() {
        return historyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_price_history.history_date
     *
     * @param historyDate the value for stock_price_history.history_date
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setHistoryDate(String historyDate) {
        this.historyDate = historyDate == null ? null : historyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_price_history.last_price
     *
     * @return the value of stock_price_history.last_price
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public Double getLastPrice() {
        return lastPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_price_history.last_price
     *
     * @param lastPrice the value for stock_price_history.last_price
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setLastPrice(Double lastPrice) {
        this.lastPrice = lastPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_price_history.closed_price
     *
     * @return the value of stock_price_history.closed_price
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public Double getClosedPrice() {
        return closedPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_price_history.closed_price
     *
     * @param closedPrice the value for stock_price_history.closed_price
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setClosedPrice(Double closedPrice) {
        this.closedPrice = closedPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_price_history.top_price
     *
     * @return the value of stock_price_history.top_price
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public Double getTopPrice() {
        return topPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_price_history.top_price
     *
     * @param topPrice the value for stock_price_history.top_price
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setTopPrice(Double topPrice) {
        this.topPrice = topPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_price_history.low_price
     *
     * @return the value of stock_price_history.low_price
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public Double getLowPrice() {
        return lowPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_price_history.low_price
     *
     * @param lowPrice the value for stock_price_history.low_price
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setLowPrice(Double lowPrice) {
        this.lowPrice = lowPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_price_history.qt_total
     *
     * @return the value of stock_price_history.qt_total
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public Long getQtTotal() {
        return qtTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_price_history.qt_total
     *
     * @param qtTotal the value for stock_price_history.qt_total
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setQtTotal(Long qtTotal) {
        this.qtTotal = qtTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_price_history.trade_count
     *
     * @return the value of stock_price_history.trade_count
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public Long getTradeCount() {
        return tradeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_price_history.trade_count
     *
     * @param tradeCount the value for stock_price_history.trade_count
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setTradeCount(Long tradeCount) {
        this.tradeCount = tradeCount;
    }
}