package com.ibm.fsd.my.stock.bkg.domain;

import java.util.Date;

public class StockBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_base.id
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_base.stock_code
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private String stockCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_base.stock_name
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private String stockName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_base.stock_count
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private Long stockCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_base.stock_count_trada
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private Long stockCountTrada;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_base.market_categ
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private String marketCateg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_base.industry_categ
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private String industryCateg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_base.issue_price
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private Double issuePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_base.suspend
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private String suspend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_base.suspend_days
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private Integer suspendDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_base.suspend_start_dt
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private Date suspendStartDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_base.last_update_dt
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private Date lastUpdateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_base.id
     *
     * @return the value of stock_base.id
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_base.id
     *
     * @param id the value for stock_base.id
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_base.stock_code
     *
     * @return the value of stock_base.stock_code
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_base.stock_code
     *
     * @param stockCode the value for stock_base.stock_code
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode == null ? null : stockCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_base.stock_name
     *
     * @return the value of stock_base.stock_name
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public String getStockName() {
        return stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_base.stock_name
     *
     * @param stockName the value for stock_base.stock_name
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setStockName(String stockName) {
        this.stockName = stockName == null ? null : stockName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_base.stock_count
     *
     * @return the value of stock_base.stock_count
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public Long getStockCount() {
        return stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_base.stock_count
     *
     * @param stockCount the value for stock_base.stock_count
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setStockCount(Long stockCount) {
        this.stockCount = stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_base.stock_count_trada
     *
     * @return the value of stock_base.stock_count_trada
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public Long getStockCountTrada() {
        return stockCountTrada;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_base.stock_count_trada
     *
     * @param stockCountTrada the value for stock_base.stock_count_trada
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setStockCountTrada(Long stockCountTrada) {
        this.stockCountTrada = stockCountTrada;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_base.market_categ
     *
     * @return the value of stock_base.market_categ
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public String getMarketCateg() {
        return marketCateg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_base.market_categ
     *
     * @param marketCateg the value for stock_base.market_categ
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setMarketCateg(String marketCateg) {
        this.marketCateg = marketCateg == null ? null : marketCateg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_base.industry_categ
     *
     * @return the value of stock_base.industry_categ
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public String getIndustryCateg() {
        return industryCateg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_base.industry_categ
     *
     * @param industryCateg the value for stock_base.industry_categ
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setIndustryCateg(String industryCateg) {
        this.industryCateg = industryCateg == null ? null : industryCateg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_base.issue_price
     *
     * @return the value of stock_base.issue_price
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public Double getIssuePrice() {
        return issuePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_base.issue_price
     *
     * @param issuePrice the value for stock_base.issue_price
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setIssuePrice(Double issuePrice) {
        this.issuePrice = issuePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_base.suspend
     *
     * @return the value of stock_base.suspend
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public String getSuspend() {
        return suspend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_base.suspend
     *
     * @param suspend the value for stock_base.suspend
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setSuspend(String suspend) {
        this.suspend = suspend == null ? null : suspend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_base.suspend_days
     *
     * @return the value of stock_base.suspend_days
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public Integer getSuspendDays() {
        return suspendDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_base.suspend_days
     *
     * @param suspendDays the value for stock_base.suspend_days
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setSuspendDays(Integer suspendDays) {
        this.suspendDays = suspendDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_base.suspend_start_dt
     *
     * @return the value of stock_base.suspend_start_dt
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public Date getSuspendStartDt() {
        return suspendStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_base.suspend_start_dt
     *
     * @param suspendStartDt the value for stock_base.suspend_start_dt
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setSuspendStartDt(Date suspendStartDt) {
        this.suspendStartDt = suspendStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_base.last_update_dt
     *
     * @return the value of stock_base.last_update_dt
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public Date getLastUpdateDt() {
        return lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_base.last_update_dt
     *
     * @param lastUpdateDt the value for stock_base.last_update_dt
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setLastUpdateDt(Date lastUpdateDt) {
        this.lastUpdateDt = lastUpdateDt;
    }
}