package com.ibm.fsd.my.stock.bkg.domain;

import java.util.Date;

public class StockConsignbuyRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_consign_buy_record.id
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_consign_buy_record.stock_id
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private Long stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_consign_buy_record.user_id
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_consign_buy_record.fund_id
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private Long fundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_consign_buy_record.consign_type
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private String consignType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_consign_buy_record.consign_price
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private Long consignPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_consign_buy_record.consign_qt
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private Long consignQt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_consign_buy_record.remains_qt
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private Long remainsQt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_consign_buy_record.consign_dt
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private Date consignDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_consign_buy_record.stauts
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    private String stauts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_consign_buy_record.id
     *
     * @return the value of stock_consign_buy_record.id
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_consign_buy_record.id
     *
     * @param id the value for stock_consign_buy_record.id
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_consign_buy_record.stock_id
     *
     * @return the value of stock_consign_buy_record.stock_id
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public Long getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_consign_buy_record.stock_id
     *
     * @param stockId the value for stock_consign_buy_record.stock_id
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setStockId(Long stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_consign_buy_record.user_id
     *
     * @return the value of stock_consign_buy_record.user_id
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_consign_buy_record.user_id
     *
     * @param userId the value for stock_consign_buy_record.user_id
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_consign_buy_record.fund_id
     *
     * @return the value of stock_consign_buy_record.fund_id
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public Long getFundId() {
        return fundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_consign_buy_record.fund_id
     *
     * @param fundId the value for stock_consign_buy_record.fund_id
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setFundId(Long fundId) {
        this.fundId = fundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_consign_buy_record.consign_type
     *
     * @return the value of stock_consign_buy_record.consign_type
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public String getConsignType() {
        return consignType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_consign_buy_record.consign_type
     *
     * @param consignType the value for stock_consign_buy_record.consign_type
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setConsignType(String consignType) {
        this.consignType = consignType == null ? null : consignType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_consign_buy_record.consign_price
     *
     * @return the value of stock_consign_buy_record.consign_price
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public Long getConsignPrice() {
        return consignPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_consign_buy_record.consign_price
     *
     * @param consignPrice the value for stock_consign_buy_record.consign_price
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setConsignPrice(Long consignPrice) {
        this.consignPrice = consignPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_consign_buy_record.consign_qt
     *
     * @return the value of stock_consign_buy_record.consign_qt
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public Long getConsignQt() {
        return consignQt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_consign_buy_record.consign_qt
     *
     * @param consignQt the value for stock_consign_buy_record.consign_qt
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setConsignQt(Long consignQt) {
        this.consignQt = consignQt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_consign_buy_record.remains_qt
     *
     * @return the value of stock_consign_buy_record.remains_qt
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public Long getRemainsQt() {
        return remainsQt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_consign_buy_record.remains_qt
     *
     * @param remainsQt the value for stock_consign_buy_record.remains_qt
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setRemainsQt(Long remainsQt) {
        this.remainsQt = remainsQt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_consign_buy_record.consign_dt
     *
     * @return the value of stock_consign_buy_record.consign_dt
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public Date getConsignDt() {
        return consignDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_consign_buy_record.consign_dt
     *
     * @param consignDt the value for stock_consign_buy_record.consign_dt
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setConsignDt(Date consignDt) {
        this.consignDt = consignDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_consign_buy_record.stauts
     *
     * @return the value of stock_consign_buy_record.stauts
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public String getStauts() {
        return stauts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_consign_buy_record.stauts
     *
     * @param stauts the value for stock_consign_buy_record.stauts
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    public void setStauts(String stauts) {
        this.stauts = stauts == null ? null : stauts.trim();
    }
}