package com.ibm.fsd.my.stock.bkg.domain;

import java.util.Date;

public class UserBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.id
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.username
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.password
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.mobile
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.available
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    private String available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.is_admin
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    private String isAdmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.last_login_dt
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    private Date lastLoginDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.online
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    private String online;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.id
     *
     * @return the value of user_base.id
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.id
     *
     * @param id the value for user_base.id
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.username
     *
     * @return the value of user_base.username
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.username
     *
     * @param username the value for user_base.username
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.password
     *
     * @return the value of user_base.password
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.password
     *
     * @param password the value for user_base.password
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.mobile
     *
     * @return the value of user_base.mobile
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.mobile
     *
     * @param mobile the value for user_base.mobile
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.available
     *
     * @return the value of user_base.available
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    public String getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.available
     *
     * @param available the value for user_base.available
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    public void setAvailable(String available) {
        this.available = available == null ? null : available.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.is_admin
     *
     * @return the value of user_base.is_admin
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    public String getIsAdmin() {
        return isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.is_admin
     *
     * @param isAdmin the value for user_base.is_admin
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    public void setIsAdmin(String isAdmin) {
        this.isAdmin = isAdmin == null ? null : isAdmin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.last_login_dt
     *
     * @return the value of user_base.last_login_dt
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    public Date getLastLoginDt() {
        return lastLoginDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.last_login_dt
     *
     * @param lastLoginDt the value for user_base.last_login_dt
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    public void setLastLoginDt(Date lastLoginDt) {
        this.lastLoginDt = lastLoginDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.online
     *
     * @return the value of user_base.online
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    public String getOnline() {
        return online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.online
     *
     * @param online the value for user_base.online
     *
     * @mbggenerated Sat Apr 25 21:20:28 CST 2020
     */
    public void setOnline(String online) {
        this.online = online == null ? null : online.trim();
    }
}