package com.ibm.fsd.my.stock.bkg.domain;

import java.util.Date;

public class UserFund {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fund.id
     *
     * @mbggenerated Sat Apr 25 21:20:29 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fund.user_id
     *
     * @mbggenerated Sat Apr 25 21:20:29 CST 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fund.fund_type
     *
     * @mbggenerated Sat Apr 25 21:20:29 CST 2020
     */
    private String fundType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fund.fund_price
     *
     * @mbggenerated Sat Apr 25 21:20:29 CST 2020
     */
    private Double fundPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fund.completed
     *
     * @mbggenerated Sat Apr 25 21:20:29 CST 2020
     */
    private String completed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fund.last_update_dt
     *
     * @mbggenerated Sat Apr 25 21:20:29 CST 2020
     */
    private Date lastUpdateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fund.id
     *
     * @return the value of user_fund.id
     *
     * @mbggenerated Sat Apr 25 21:20:29 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fund.id
     *
     * @param id the value for user_fund.id
     *
     * @mbggenerated Sat Apr 25 21:20:29 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fund.user_id
     *
     * @return the value of user_fund.user_id
     *
     * @mbggenerated Sat Apr 25 21:20:29 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fund.user_id
     *
     * @param userId the value for user_fund.user_id
     *
     * @mbggenerated Sat Apr 25 21:20:29 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fund.fund_type
     *
     * @return the value of user_fund.fund_type
     *
     * @mbggenerated Sat Apr 25 21:20:29 CST 2020
     */
    public String getFundType() {
        return fundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fund.fund_type
     *
     * @param fundType the value for user_fund.fund_type
     *
     * @mbggenerated Sat Apr 25 21:20:29 CST 2020
     */
    public void setFundType(String fundType) {
        this.fundType = fundType == null ? null : fundType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fund.fund_price
     *
     * @return the value of user_fund.fund_price
     *
     * @mbggenerated Sat Apr 25 21:20:29 CST 2020
     */
    public Double getFundPrice() {
        return fundPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fund.fund_price
     *
     * @param fundPrice the value for user_fund.fund_price
     *
     * @mbggenerated Sat Apr 25 21:20:29 CST 2020
     */
    public void setFundPrice(Double fundPrice) {
        this.fundPrice = fundPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fund.completed
     *
     * @return the value of user_fund.completed
     *
     * @mbggenerated Sat Apr 25 21:20:29 CST 2020
     */
    public String getCompleted() {
        return completed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fund.completed
     *
     * @param completed the value for user_fund.completed
     *
     * @mbggenerated Sat Apr 25 21:20:29 CST 2020
     */
    public void setCompleted(String completed) {
        this.completed = completed == null ? null : completed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fund.last_update_dt
     *
     * @return the value of user_fund.last_update_dt
     *
     * @mbggenerated Sat Apr 25 21:20:29 CST 2020
     */
    public Date getLastUpdateDt() {
        return lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fund.last_update_dt
     *
     * @param lastUpdateDt the value for user_fund.last_update_dt
     *
     * @mbggenerated Sat Apr 25 21:20:29 CST 2020
     */
    public void setLastUpdateDt(Date lastUpdateDt) {
        this.lastUpdateDt = lastUpdateDt;
    }
}