node {
   stage('git clone') { // for display purposes
     checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'gitlab', url: 'https://github.com/byron998/fullstack.git']]])
   }
   stage('Build') {
           //env.JAVA_HOME="${tool 'jdk1.8.0_231'}"
           withMaven(
            maven: 'maven',
            mavenLocalRepo: '.repository') {
                sh "mvn clean install -Dmaven.test.skip=true"
        }
   }
   stage('deploy') {
   		steps{
            echo 'push jar to target server'
            sh '''
                ole_image_id=`docker images|grep ${IMAGE_NAME}|grep ${VERSION_ID}|awk '{print $3}'`
                if [[ -n "${ole_image_id}" ]]; then
                    docker rmi -f ${ole_image_id}
                fi
                
                docker build -f Dockerfile --build-arg jar_name=${JAR_NAME} -t ${IMAGE_NAME}:${VERSION_ID} .
                
                new_image_id=`docker images|grep ${IMAGE_NAME}|grep ${VERSION_ID}|awk '{print $3}'`
                sudo docker tag ${new_image_id} ${IMAGE_ADDR}:${VERSION_ID}
                sudo docker push ${IMAGE_ADDR}:${VERSION_ID}
            '''
		}
	}
	
}