package com.ibm.fsd.my.stock.bkg.mapper;

import com.ibm.fsd.my.stock.bkg.domain.StockConsignSellRecord;

public interface StockConsignSellRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_consign_sell_record
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_consign_sell_record
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    int insert(StockConsignSellRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_consign_sell_record
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    int insertSelective(StockConsignSellRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_consign_sell_record
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    StockConsignSellRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_consign_sell_record
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    int updateByPrimaryKeySelective(StockConsignSellRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_consign_sell_record
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    int updateByPrimaryKey(StockConsignSellRecord record);
}