package com.ibm.fsd.my.stock.bkg.mapper;

import com.ibm.fsd.my.stock.bkg.domain.StockBase;

public interface StockBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_base
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_base
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    int insert(StockBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_base
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    int insertSelective(StockBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_base
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    StockBase selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_base
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    int updateByPrimaryKeySelective(StockBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_base
     *
     * @mbggenerated Sat Apr 25 23:44:18 CST 2020
     */
    int updateByPrimaryKey(StockBase record);
}