package com.ibm.fsd.my.stock.bkg.mapper;

import com.ibm.fsd.my.stock.bkg.domain.StockPriceHistory;

public interface StockPriceHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_history
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_history
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    int insert(StockPriceHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_history
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    int insertSelective(StockPriceHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_history
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    StockPriceHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_history
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    int updateByPrimaryKeySelective(StockPriceHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_history
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    int updateByPrimaryKey(StockPriceHistory record);
}