package com.ibm.fsd.my.stock.bkg.mapper;

import com.ibm.fsd.my.stock.bkg.domain.UserFund;

public interface UserFundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    int insert(UserFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    int insertSelective(UserFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    UserFund selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    int updateByPrimaryKeySelective(UserFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund
     *
     * @mbggenerated Sun May 10 22:26:47 CST 2020
     */
    int updateByPrimaryKey(UserFund record);
}